(ns gddr_memory.actor
  "gddr_memory clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). GDDR6 / GDDR7 graphics memory design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; GddrDevice
   {:db/ident :gddr_memory.GddrDevice/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gddr_memory.GddrDevice/partNumber :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.GddrDevice/generation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.GddrDevice/capacityGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.GddrDevice/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.GddrDevice/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.GddrDevice/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MemoryChannel
   {:db/ident :gddr_memory.MemoryChannel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gddr_memory.MemoryChannel/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.MemoryChannel/width :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.MemoryChannel/prefetch :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.MemoryChannel/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.MemoryChannel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.MemoryChannel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SignalingMode
   {:db/ident :gddr_memory.SignalingMode/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gddr_memory.SignalingMode/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SignalingMode/scheme :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SignalingMode/levels :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SignalingMode/eyeHeightMv :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SignalingMode/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SignalingMode/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ThermalProfile
   {:db/ident :gddr_memory.ThermalProfile/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gddr_memory.ThermalProfile/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.ThermalProfile/tjMaxC :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.ThermalProfile/powerW :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.ThermalProfile/throttle :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.ThermalProfile/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.ThermalProfile/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SpeedGrade
   {:db/ident :gddr_memory.SpeedGrade/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gddr_memory.SpeedGrade/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SpeedGrade/grade :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SpeedGrade/voltage :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SpeedGrade/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SpeedGrade/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.SpeedGrade/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; TestBin
   {:db/ident :gddr_memory.TestBin/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gddr_memory.TestBin/deviceId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.TestBin/binCode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.TestBin/yield :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.TestBin/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.TestBin/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gddr_memory.TestBin/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"GddrDevice" "MemoryChannel" "SignalingMode" "ThermalProfile" "SpeedGrade" "TestBin"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "gddr_memory: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "gddr_memory: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "gddr_memory: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── GddrDevice ────────────────────────────────────────────────────────────────
(defn create-gddr-device
  "Create a GddrDevice."
  [port data]
  (require-fields data ["partNumber" "generation"])
  (let [id (new-id "gddr_gdd")
        e {:db/id id
           :gddr_memory.GddrDevice/id id
           :gddr_memory.GddrDevice/partNumber (get data :partNumber)
           :gddr_memory.GddrDevice/generation (get data :generation)
           :gddr_memory.GddrDevice/capacityGb (as-long (get data :capacityGb))
           :gddr_memory.GddrDevice/dataRateGbps (as-double (get data :dataRateGbps))
           :gddr_memory.GddrDevice/createdAt (now)
           :gddr_memory.GddrDevice/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-gddr-devices
  "List GddrDevice with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-gddr-devices port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gddr_memory.GddrDevice/id))
         rows (apply-filters rows (:filter opts) [:gddr_memory.GddrDevice/partNumber :gddr_memory.GddrDevice/generation :gddr_memory.GddrDevice/capacityGb :gddr_memory.GddrDevice/dataRateGbps])]
     (paginate rows opts))))

(defn get-gddr-device
  "Retrieve a GddrDevice by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-gddr-device port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-gddr-device
  "Update a GddrDevice; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :partNumber) (conj [:db/add id :gddr_memory.GddrDevice/partNumber (get data :partNumber)]))
                   (cond-> (contains? data :generation) (conj [:db/add id :gddr_memory.GddrDevice/generation (get data :generation)]))
                   (cond-> (contains? data :capacityGb) (conj [:db/add id :gddr_memory.GddrDevice/capacityGb (as-long (get data :capacityGb))]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :gddr_memory.GddrDevice/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (conj [:db/add id :gddr_memory.GddrDevice/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-gddr-device
  "Delete a GddrDevice."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MemoryChannel ────────────────────────────────────────────────────────────────
(defn create-memory-channel
  "Create a MemoryChannel."
  [port data]
  (require-fields data ["width" "prefetch"])
  (let [id (new-id "gddr_mem")
        e {:db/id id
           :gddr_memory.MemoryChannel/id id
           :gddr_memory.MemoryChannel/deviceId (get data :deviceId)
           :gddr_memory.MemoryChannel/width (as-long (get data :width))
           :gddr_memory.MemoryChannel/prefetch (as-long (get data :prefetch))
           :gddr_memory.MemoryChannel/dataRateGbps (as-double (get data :dataRateGbps))
           :gddr_memory.MemoryChannel/createdAt (now)
           :gddr_memory.MemoryChannel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-memory-channels
  "List MemoryChannel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-memory-channels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gddr_memory.MemoryChannel/id))
         rows (apply-filters rows (:filter opts) [:gddr_memory.MemoryChannel/deviceId :gddr_memory.MemoryChannel/width :gddr_memory.MemoryChannel/prefetch :gddr_memory.MemoryChannel/dataRateGbps])]
     (paginate rows opts))))

(defn get-memory-channel
  "Retrieve a MemoryChannel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-memory-channel port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-memory-channel
  "Update a MemoryChannel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :gddr_memory.MemoryChannel/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :width) (conj [:db/add id :gddr_memory.MemoryChannel/width (as-long (get data :width))]))
                   (cond-> (contains? data :prefetch) (conj [:db/add id :gddr_memory.MemoryChannel/prefetch (as-long (get data :prefetch))]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :gddr_memory.MemoryChannel/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (conj [:db/add id :gddr_memory.MemoryChannel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-memory-channel
  "Delete a MemoryChannel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SignalingMode ────────────────────────────────────────────────────────────────
(defn create-signaling-mode
  "Create a SignalingMode."
  [port data]
  (require-fields data ["scheme" "levels"])
  (let [id (new-id "gddr_sig")
        e {:db/id id
           :gddr_memory.SignalingMode/id id
           :gddr_memory.SignalingMode/deviceId (get data :deviceId)
           :gddr_memory.SignalingMode/scheme (get data :scheme)
           :gddr_memory.SignalingMode/levels (as-long (get data :levels))
           :gddr_memory.SignalingMode/eyeHeightMv (as-double (get data :eyeHeightMv))
           :gddr_memory.SignalingMode/createdAt (now)
           :gddr_memory.SignalingMode/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-signaling-modes
  "List SignalingMode with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-signaling-modes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gddr_memory.SignalingMode/id))
         rows (apply-filters rows (:filter opts) [:gddr_memory.SignalingMode/deviceId :gddr_memory.SignalingMode/scheme :gddr_memory.SignalingMode/levels :gddr_memory.SignalingMode/eyeHeightMv])]
     (paginate rows opts))))

(defn get-signaling-mode
  "Retrieve a SignalingMode by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-signaling-mode port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-signaling-mode
  "Update a SignalingMode; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :gddr_memory.SignalingMode/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :scheme) (conj [:db/add id :gddr_memory.SignalingMode/scheme (get data :scheme)]))
                   (cond-> (contains? data :levels) (conj [:db/add id :gddr_memory.SignalingMode/levels (as-long (get data :levels))]))
                   (cond-> (contains? data :eyeHeightMv) (conj [:db/add id :gddr_memory.SignalingMode/eyeHeightMv (as-double (get data :eyeHeightMv))]))
                   (conj [:db/add id :gddr_memory.SignalingMode/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-signaling-mode
  "Delete a SignalingMode."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ThermalProfile ────────────────────────────────────────────────────────────────
(defn create-thermal-profile
  "Create a ThermalProfile."
  [port data]
  (require-fields data ["tjMaxC" "powerW"])
  (let [id (new-id "gddr_the")
        e {:db/id id
           :gddr_memory.ThermalProfile/id id
           :gddr_memory.ThermalProfile/deviceId (get data :deviceId)
           :gddr_memory.ThermalProfile/tjMaxC (as-double (get data :tjMaxC))
           :gddr_memory.ThermalProfile/powerW (as-double (get data :powerW))
           :gddr_memory.ThermalProfile/throttle (as-bool (get data :throttle))
           :gddr_memory.ThermalProfile/createdAt (now)
           :gddr_memory.ThermalProfile/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-thermal-profiles
  "List ThermalProfile with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-thermal-profiles port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gddr_memory.ThermalProfile/id))
         rows (apply-filters rows (:filter opts) [:gddr_memory.ThermalProfile/deviceId :gddr_memory.ThermalProfile/tjMaxC :gddr_memory.ThermalProfile/powerW :gddr_memory.ThermalProfile/throttle])]
     (paginate rows opts))))

(defn get-thermal-profile
  "Retrieve a ThermalProfile by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-thermal-profile port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-thermal-profile
  "Update a ThermalProfile; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :gddr_memory.ThermalProfile/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :tjMaxC) (conj [:db/add id :gddr_memory.ThermalProfile/tjMaxC (as-double (get data :tjMaxC))]))
                   (cond-> (contains? data :powerW) (conj [:db/add id :gddr_memory.ThermalProfile/powerW (as-double (get data :powerW))]))
                   (cond-> (contains? data :throttle) (conj [:db/add id :gddr_memory.ThermalProfile/throttle (as-bool (get data :throttle))]))
                   (conj [:db/add id :gddr_memory.ThermalProfile/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-thermal-profile
  "Delete a ThermalProfile."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SpeedGrade ────────────────────────────────────────────────────────────────
(defn create-speed-grade
  "Create a SpeedGrade."
  [port data]
  (require-fields data ["grade" "voltage"])
  (let [id (new-id "gddr_spe")
        e {:db/id id
           :gddr_memory.SpeedGrade/id id
           :gddr_memory.SpeedGrade/deviceId (get data :deviceId)
           :gddr_memory.SpeedGrade/grade (get data :grade)
           :gddr_memory.SpeedGrade/voltage (as-double (get data :voltage))
           :gddr_memory.SpeedGrade/dataRateGbps (as-double (get data :dataRateGbps))
           :gddr_memory.SpeedGrade/createdAt (now)
           :gddr_memory.SpeedGrade/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-speed-grades
  "List SpeedGrade with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-speed-grades port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gddr_memory.SpeedGrade/id))
         rows (apply-filters rows (:filter opts) [:gddr_memory.SpeedGrade/deviceId :gddr_memory.SpeedGrade/grade :gddr_memory.SpeedGrade/voltage :gddr_memory.SpeedGrade/dataRateGbps])]
     (paginate rows opts))))

(defn get-speed-grade
  "Retrieve a SpeedGrade by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-speed-grade port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-speed-grade
  "Update a SpeedGrade; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :gddr_memory.SpeedGrade/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :grade) (conj [:db/add id :gddr_memory.SpeedGrade/grade (get data :grade)]))
                   (cond-> (contains? data :voltage) (conj [:db/add id :gddr_memory.SpeedGrade/voltage (as-double (get data :voltage))]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :gddr_memory.SpeedGrade/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (conj [:db/add id :gddr_memory.SpeedGrade/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-speed-grade
  "Delete a SpeedGrade."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── TestBin ────────────────────────────────────────────────────────────────
(defn create-test-bin
  "Create a TestBin."
  [port data]
  (require-fields data ["binCode" "yield"])
  (let [id (new-id "gddr_tes")
        e {:db/id id
           :gddr_memory.TestBin/id id
           :gddr_memory.TestBin/deviceId (get data :deviceId)
           :gddr_memory.TestBin/binCode (get data :binCode)
           :gddr_memory.TestBin/yield (as-double (get data :yield))
           :gddr_memory.TestBin/status (get data :status)
           :gddr_memory.TestBin/createdAt (now)
           :gddr_memory.TestBin/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-test-bins
  "List TestBin with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-test-bins port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gddr_memory.TestBin/id))
         rows (apply-filters rows (:filter opts) [:gddr_memory.TestBin/deviceId :gddr_memory.TestBin/binCode :gddr_memory.TestBin/yield :gddr_memory.TestBin/status])]
     (paginate rows opts))))

(defn get-test-bin
  "Retrieve a TestBin by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-test-bin port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-test-bin
  "Update a TestBin; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :deviceId) (conj [:db/add id :gddr_memory.TestBin/deviceId (get data :deviceId)]))
                   (cond-> (contains? data :binCode) (conj [:db/add id :gddr_memory.TestBin/binCode (get data :binCode)]))
                   (cond-> (contains? data :yield) (conj [:db/add id :gddr_memory.TestBin/yield (as-double (get data :yield))]))
                   (cond-> (contains? data :status) (conj [:db/add id :gddr_memory.TestBin/status (get data :status)]))
                   (conj [:db/add id :gddr_memory.TestBin/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-test-bin
  "Delete a TestBin."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/gddrdevices" :op :create :entity "GddrDevice"}
   {:method "GET" :path "/v1/gddrdevices" :op :list :entity "GddrDevice"}
   {:method "GET" :path "/v1/gddrdevices/:id" :op :get :entity "GddrDevice"}
   {:method "PATCH" :path "/v1/gddrdevices/:id" :op :update :entity "GddrDevice"}
   {:method "DELETE" :path "/v1/gddrdevices/:id" :op :delete :entity "GddrDevice"}
   {:method "POST" :path "/v1/memorychannels" :op :create :entity "MemoryChannel"}
   {:method "GET" :path "/v1/memorychannels" :op :list :entity "MemoryChannel"}
   {:method "GET" :path "/v1/memorychannels/:id" :op :get :entity "MemoryChannel"}
   {:method "PATCH" :path "/v1/memorychannels/:id" :op :update :entity "MemoryChannel"}
   {:method "DELETE" :path "/v1/memorychannels/:id" :op :delete :entity "MemoryChannel"}
   {:method "POST" :path "/v1/signalingmodes" :op :create :entity "SignalingMode"}
   {:method "GET" :path "/v1/signalingmodes" :op :list :entity "SignalingMode"}
   {:method "GET" :path "/v1/signalingmodes/:id" :op :get :entity "SignalingMode"}
   {:method "PATCH" :path "/v1/signalingmodes/:id" :op :update :entity "SignalingMode"}
   {:method "DELETE" :path "/v1/signalingmodes/:id" :op :delete :entity "SignalingMode"}
   {:method "POST" :path "/v1/thermalprofiles" :op :create :entity "ThermalProfile"}
   {:method "GET" :path "/v1/thermalprofiles" :op :list :entity "ThermalProfile"}
   {:method "GET" :path "/v1/thermalprofiles/:id" :op :get :entity "ThermalProfile"}
   {:method "PATCH" :path "/v1/thermalprofiles/:id" :op :update :entity "ThermalProfile"}
   {:method "DELETE" :path "/v1/thermalprofiles/:id" :op :delete :entity "ThermalProfile"}
   {:method "POST" :path "/v1/speedgrades" :op :create :entity "SpeedGrade"}
   {:method "GET" :path "/v1/speedgrades" :op :list :entity "SpeedGrade"}
   {:method "GET" :path "/v1/speedgrades/:id" :op :get :entity "SpeedGrade"}
   {:method "PATCH" :path "/v1/speedgrades/:id" :op :update :entity "SpeedGrade"}
   {:method "DELETE" :path "/v1/speedgrades/:id" :op :delete :entity "SpeedGrade"}
   {:method "POST" :path "/v1/testbins" :op :create :entity "TestBin"}
   {:method "GET" :path "/v1/testbins" :op :list :entity "TestBin"}
   {:method "GET" :path "/v1/testbins/:id" :op :get :entity "TestBin"}
   {:method "PATCH" :path "/v1/testbins/:id" :op :update :entity "TestBin"}
   {:method "DELETE" :path "/v1/testbins/:id" :op :delete :entity "TestBin"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"gddrdevices" {:create create-gddr-device :list list-gddr-devices :get get-gddr-device :update update-gddr-device :delete delete-gddr-device}
   "memorychannels" {:create create-memory-channel :list list-memory-channels :get get-memory-channel :update update-memory-channel :delete delete-memory-channel}
   "signalingmodes" {:create create-signaling-mode :list list-signaling-modes :get get-signaling-mode :update update-signaling-mode :delete delete-signaling-mode}
   "thermalprofiles" {:create create-thermal-profile :list list-thermal-profiles :get get-thermal-profile :update update-thermal-profile :delete delete-thermal-profile}
   "speedgrades" {:create create-speed-grade :list list-speed-grades :get get-speed-grade :update update-speed-grade :delete delete-speed-grade}
   "testbins" {:create create-test-bin :list list-test-bins :get get-test-bin :update update-test-bin :delete delete-test-bin}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "gddr_memory-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
